name: CI

on: [push]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: use node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install deps
      run: npm install
    - name: run tests
      run: npm test
